export enum ReportReason {
  HARASSMENT = 'HARASSMENT',
  HATE_SPEECH = 'HATE_SPEECH',
  SPAM = 'SPAM',
  IMPERSONATION = 'IMPERSONATION',
  NSFW = 'NSFW',
  VIOLENCE = 'VIOLENCE',
  MISINFORMATION = 'MISINFORMATION',
  ACADEMIC_DISHONESTY = 'ACADEMIC_DISHONESTY',
  OTHER = 'OTHER',
}
